# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eemuston <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/18 11:32:51 by eemuston          #+#    #+#              #
#    Updated: 2022/07/18 11:32:57 by eemuston         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = bsq

SRCS = 

all: $(NAME)

$(NAME): $(SRCS)
	gcc -Wall -Werror -Wextra $(SRCS) -o $(NAME) -Iincludes

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
